site_name: Taller radio libre
site_author: Iker Landajuela
google_analytics: ['UA-111273781-1', 'https://ikerlandajuela.github.io/radiolibre/']
repo_url: https://github.com/ikerlandajuela/radiolibre
pages:
    - Inicio: index.md    
    - Material: material.md
    - Manuales: 
        - 'Servidor de radio en máquina virtual': 'man/libretime_y_virtualbox.md'
        - 'Manual LibreTime': 'man/libretime.md'
        - 'Estudio colaboradores': 'man/cliente_estudio.md'
        - 'Problemas comunes': 'man/problemas_comunes.md'
    - Recursos: recursos.md
theme: readthedocs